FROM python:3.11-slim

WORKDIR /app

# Copier d'abord le fichier requirements.txt
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le reste de l'application
COPY . .

# Copier le fichier .env (si nécessaire pour la configuration)
COPY .env .env

# Exposer le port utilisé par FastAPI
EXPOSE 8080

# Lancer Uvicorn pour démarrer FastAPI
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]
